// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-98jAJ_2Scq1hb7hUACPKY5V33siNmGw',
    appId: '1:150414918658:web:127d7067e33f418005931b',
    messagingSenderId: '150414918658',
    projectId: 'movies-v2-2ae55',
    authDomain: 'movies-v2-2ae55.firebaseapp.com',
    storageBucket: 'movies-v2-2ae55.firebasestorage.app',
    measurementId: 'G-3R70R2XGNL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoVXLl0xb8BJhzU1W0Hjj4-IsSM-7IV9M',
    appId: '1:150414918658:android:bc67f86453fee05a05931b',
    messagingSenderId: '150414918658',
    projectId: 'movies-v2-2ae55',
    storageBucket: 'movies-v2-2ae55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4-dJJC1ObnFugQjUIveJTe7EsRKsy_F0',
    appId: '1:150414918658:ios:7bad80a06ee4423e05931b',
    messagingSenderId: '150414918658',
    projectId: 'movies-v2-2ae55',
    storageBucket: 'movies-v2-2ae55.firebasestorage.app',
    iosClientId: '150414918658-vrs4taj6lq3ksfvsqvc6v6nuvml1o6c2.apps.googleusercontent.com',
    iosBundleId: 'com.example.movies.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4-dJJC1ObnFugQjUIveJTe7EsRKsy_F0',
    appId: '1:150414918658:ios:c087c319bdf4d22f05931b',
    messagingSenderId: '150414918658',
    projectId: 'movies-v2-2ae55',
    storageBucket: 'movies-v2-2ae55.firebasestorage.app',
    iosClientId: '150414918658-0nfbc48tdf4rfilpfm5cag5sq0fu3k56.apps.googleusercontent.com',
    iosBundleId: 'com.example.movies',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-98jAJ_2Scq1hb7hUACPKY5V33siNmGw',
    appId: '1:150414918658:web:bb9cd5853ddf04d305931b',
    messagingSenderId: '150414918658',
    projectId: 'movies-v2-2ae55',
    authDomain: 'movies-v2-2ae55.firebaseapp.com',
    storageBucket: 'movies-v2-2ae55.firebasestorage.app',
    measurementId: 'G-PHTJM210B7',
  );
}
